language: node_js
node_js:
    - "8"

services:
    - docker

before_install:
    - docker run -d -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 elasticsearch:6.7.0

env:

script:
    - yarn install
    - yarn build
    - yarn test
